// packages/react/src/components/control/sign-out-button.tsx
import { type ReactNode, useCallback, useState } from 'react'

import { useLingui } from '@lingui/react'

import { useXidContext } from '../../context/xid-context'
import { rt, sdkMessages } from '../../i18n-runtime'

export type SignOutButtonProps = {
  children?: ReactNode
  sessionId?: string
  redirectUrl?: string
  'aria-label'?: string
}

export function SignOutButton({
  children,
  sessionId,
  redirectUrl,
  'aria-label': ariaLabel,
}: SignOutButtonProps): ReactNode {
  const { client } = useXidContext()
  const { _ } = useLingui()
  const [pending, setPending] = useState(false)

  const handleClick = useCallback(async () => {
    if (pending) return
    setPending(true)
    try {
      const result = await client.signOut({ ...(sessionId ? { sessionId } : {}) })
      if (result.ok && redirectUrl) {
        window.location.assign(redirectUrl)
      }
    } finally {
      setPending(false)
    }
  }, [client, sessionId, redirectUrl, pending])

  return (
    <button
      type="button"
      onClick={() => void handleClick()}
      aria-label={ariaLabel}
      aria-busy={pending}
      disabled={pending}
    >
      {children ?? rt(_, sdkMessages.signOut)}
    </button>
  )
}

// packages/angular/src/sign-out-button.component.ts
// 调用 XidAuthService.signOut() 的 standalone 登出按钮。

import { Component, inject, Input } from '@angular/core'

import { XidAuthService } from './xid-auth.service'

@Component({
  selector: 'xid-sign-out-button',
  standalone: true,
  template: `
    <button
      type="button"
      [attr.aria-label]="ariaLabel || null"
      [attr.aria-busy]="pending"
      [disabled]="pending"
      (click)="onClickEvent()"
    >
      <ng-content>Sign out</ng-content>
    </button>
  `,
})
export class SignOutButton {
  readonly #auth = inject(XidAuthService)

  @Input() sessionId?: string
  @Input() redirectUrl?: string
  @Input() ariaLabel?: string

  protected pending = false

  // 模板 (click) 要求同步处理器；异步登出经 void 标记的 Promise 排队。
  onClickEvent(): void {
    void this.#doSignOut()
  }

  async #doSignOut(): Promise<void> {
    if (this.pending) return
    this.pending = true
    try {
      const result = await this.#auth.signOut(
        this.sessionId ? { sessionId: this.sessionId } : undefined,
      )
      if (result.ok && this.redirectUrl) {
        window.location.assign(this.redirectUrl)
      }
    } finally {
      this.pending = false
    }
  }
}
