// packages/angular/src/sign-in-button.component.ts
// 跳转到 Hosted UI 登录页（Authorization Code + PKCE S256，由服务端完成）。

import { Component, Input } from '@angular/core'

@Component({
  selector: 'xid-sign-in-button',
  standalone: true,
  template: `
    <button type="button" [attr.aria-label]="ariaLabel || null" (click)="handleClick()">
      <ng-content>Sign in</ng-content>
    </button>
  `,
})
export class SignInButton {
  @Input() signInUrl = '/sign-in'
  @Input() redirectUrl?: string
  @Input() ariaLabel?: string

  handleClick(): void {
    const target = this.redirectUrl
      ? `${this.signInUrl}?redirect_url=${encodeURIComponent(this.redirectUrl)}`
      : this.signInUrl
    window.location.assign(target)
  }
}

// packages/react/src/components/control/sign-in-button.tsx
// SignInButton:无样式登录触发按钮(对标 Clerk <SignInButton>)。
// mode=redirect -> 跳转 Hosted UI;mode=modal -> 触发父层弹窗(需配合 <SignIn modal />)。

import type { ReactNode } from 'react'

import { useLingui } from '@lingui/react'

import { rt, sdkMessages } from '../../i18n-runtime'

export type SignInButtonProps = {
  children?: ReactNode
  // 登录页路径(Hosted UI)
  signInUrl?: string
  // 登录成功后跳转
  redirectUrl?: string
  mode?: 'redirect'
  // a11y
  'aria-label'?: string
}

export function SignInButton({
  children,
  signInUrl = '/sign-in',
  redirectUrl,
  'aria-label': ariaLabel,
}: SignInButtonProps): ReactNode {
  const { _ } = useLingui()

  function handleClick(): void {
    const target = redirectUrl
      ? `${signInUrl}?redirect_url=${encodeURIComponent(redirectUrl)}`
      : signInUrl
    window.location.assign(target)
  }

  return (
    <button type="button" onClick={handleClick} aria-label={ariaLabel}>
      {children ?? rt(_, sdkMessages.signIn)}
    </button>
  )
}
